In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston #보스턴 주택값 데이터

In [3]:
boston=load_boston()

In [8]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [9]:
print(boston.filename)

C:\Users\SMT063\anaconda3\lib\site-packages\sklearn\datasets\data\boston_house_prices.csv

In [11]:
#boston의 data를 DataFrame로 만들기

pd.DataFrame(boston.data, columns=boston.feature_names)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [12]:
pd.DataFrame(boston['data'], columns=boston['feature_names'])

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [13]:
boston_df=pd.DataFrame(boston.data, columns=boston.feature_names)
boston_df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [14]:
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
#y 데이터,boston의 target값 사용
house_price=boston.target

### train과 test로 분리

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(boston_df,house_price)

In [1]:
from sklearn.linear_model import Lasso,Ridge

In [24]:
#copy
boston_copy=X_train.copy()#copy로 해놓으면 X_train값이 바뀌는 일이 없다
boston_copy['Price']=y_train
boston_copy

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
450,6.71772,0.0,18.10,0.0,0.713,6.749,92.6,2.3236,24.0,666.0,20.2,0.32,17.44,13.4
121,0.07165,0.0,25.65,0.0,0.581,6.004,84.1,2.1974,2.0,188.0,19.1,377.67,14.27,20.3
174,0.08447,0.0,4.05,0.0,0.510,5.859,68.7,2.7019,5.0,296.0,16.6,393.23,9.64,22.6
103,0.21161,0.0,8.56,0.0,0.520,6.137,87.4,2.7147,5.0,384.0,20.9,394.47,13.44,19.3
406,20.71620,0.0,18.10,0.0,0.659,4.138,100.0,1.1781,24.0,666.0,20.2,370.22,23.34,11.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,0.09068,45.0,3.44,0.0,0.437,6.951,21.5,6.4798,5.0,398.0,15.2,377.68,5.10,37.0
334,0.03738,0.0,5.19,0.0,0.515,6.310,38.5,6.4584,5.0,224.0,20.2,389.40,6.75,20.7
206,0.22969,0.0,10.59,0.0,0.489,6.326,52.5,4.3549,4.0,277.0,18.6,394.87,10.97,24.4
356,8.98296,0.0,18.10,1.0,0.770,6.212,97.4,2.1222,24.0,666.0,20.2,377.73,17.60,17.8
129,0.88125,0.0,21.89,0.0,0.624,5.637,94.7,1.9799,4.0,437.0,21.2,396.90,18.34,14.3

In [25]:
boston_copy.corr()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
CRIM,1.000000,-0.208083,0.403540,-0.044219,0.424286,-0.280597,0.368572,-0.380711,0.659617,0.606272,0.296340,-0.446926,0.461318,-0.361328
ZN,-0.208083,1.000000,-0.525925,-0.051009,-0.506132,0.289992,-0.558791,0.681093,-0.301099,-0.311504,-0.388683,0.159450,-0.394653,0.332633
INDUS,0.403540,-0.525925,1.000000,0.059382,0.739835,-0.426317,0.638155,-0.692374,0.542714,0.694232,0.380752,-0.330848,0.620256,-0.484303
CHAS,-0.044219,-0.051009,0.059382,1.000000,0.094387,0.099773,0.110575,-0.111159,0.003146,-0.026355,-0.124312,0.027751,-0.030177,0.165258
NOX,0.424286,-0.506132,0.739835,0.094387,1.000000,-0.327969,0.730767,-0.764082,0.566192,0.635407,0.148169,-0.370878,0.602029,-0.410599
RM,-0.280597,0.289992,-0.426317,0.099773,-0.327969,1.000000,-0.248726,0.209323,-0.238424,-0.333546,-0.380894,0.128786,-0.651727,0.750254
AGE,0.368572,-0.558791,0.638155,0.110575,0.730767,-0.248726,1.000000,-0.751611,0.422238,0.482895,0.248678,-0.253057,0.609720,-0.358905
DIS,-0.380711,0.681093,-0.692374,-0.111159,-0.764082,0.209323,-0.751611,1.000000,-0.458862,-0.501973,-0.206427,0.264842,-0.497740,0.226601
RAD,0.659617,-0.301099,0.542714,0.003146,0.566192,-0.238424,0.422238,-0.458862,1.000000,0.892501,0.460389,-0.399960,0.453935,-0.351275
TAX,0.606272,-0.311504,0.694232,-0.026355,0.635407,-0.333546,0.482895,-0.501973,0.892501,1.000000,0.459379,-0.402531,0.528235,-0.462039
PTRATIO,0.296340,-0.388683,0.380752,-0.124312,0.148169,-0.380894,0.248678,-0.206427,0.460389,0.459379,1.000000,-0.135665,0.358725,-0.502625
B,-0.446926,0.159450,-0.330848,0.027751,-0.370878,0.128786,-0.253057,0.264842,-0.399960,-0.402531,-0.135665,1.000000,-0.324860,0.312150
LSTAT,0.461318,-0.394653,0.620256,-0.030177,0.602029,-0.651727,0.609720,-0.497740,0.453935,0.528235,0.358725,-0.324860,1.000000,-0.727896
Price,-0.361328,0.332633,-0.484303,0.165258,-0.410599,0.750254,-0.358905,0.226601,-0.351275,-0.462039,-0.502625,0.312150,-0.727896,1.000000

In [26]:
#특성 확장
#칼럼값을 곱해서 새로운 칼럼을 만들자
extend_X_train=X_train.copy()
for col1 in X_train.columns:
    for col2 in X_train.columns:
        extend_X_train[col1+"x"+col2]=X_train[col1]*X_train[col2]

In [28]:
extend_X_train.shape

(379, 182)

In [29]:
extend_X_test=X_test.copy()
for col1 in X_test.columns:
    for col2 in X_test.columns:
        extend_X_test[col1+"x"+col2]=X_test[col1]*X_test[col2]

extend_X_test.shape

### 1. 셀 합치기
- edit모드에서 shift +m

### 2. 셀 나누기
- command모드에서 ctrl+shift+-

### Lasso

In [48]:
lasso=Lasso(alpha=1)
lasso.fit(extend_X_train,y_train)
print(lasso.score(extend_X_train,y_train))
print(lasso.score(extend_X_test,y_test))
print(np.sum(lasso.coef_!=0))#사용한 특성의 개수

0.8771482922267895
0.8110725861932822
88

C:\Users\SMT063\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2172.0424035072974, tolerance: 3.1442449762532982
  model = cd_fast.enet_coordinate_descent(

In [49]:
#모든 특성의 가중치
lasso.coef_

array([ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  1.34177702e-02, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  4.33373432e-03,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.25834869e-02,
       -0.00000000e+00, -2.00141955e-02,  4.80584306e-05,  0.00000000e+00,
        6.09442773e-04,  0.00000000e+00,  0.00000000e+00,  3.06187548e-04,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.75251917e-02,
        4.47630021e-05, -0.00000000e+00, -3.17032712e-06,  6.23655274e-05,
        1.44706633e-04, -5.56027392e-04, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  6.40264259e-04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -1.38885447e-02,
       -4.25855000e-04, -1.23629867e-02,  9.55314236e-05, -1.97177848e-02,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.14177899e-03,  0.00000000e+00, -4.12994758e-04,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -6.98789164e-03, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  6.42990337e-03,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        2.43582082e-02,  0.00000000e+00, -6.32760591e-03, -9.16597242e-03,
       -0.00000000e+00,  7.51173676e-03, -0.00000000e+00,  1.62011833e-02,
        5.84395127e-05,  9.20930371e-03,  0.00000000e+00,  0.00000000e+00,
        1.23258386e-03,  3.39264252e-04,  1.00254690e-02, -3.27956172e-03,
       -2.26867398e-04,  0.00000000e+00, -3.96098808e-04, -4.58292577e-03,
       -0.00000000e+00, -2.04374200e-03, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  2.10912902e-03,  1.27599294e-01,
       -0.00000000e+00, -4.18811377e-03,  0.00000000e+00, -3.86288440e-03,
        0.00000000e+00, -0.00000000e+00, -3.83549547e-03,  8.35996583e-03,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  3.43958526e-03,
       -0.00000000e+00, -3.31629577e-02,  1.40508590e-03,  3.43599656e-02,
       -5.81362213e-04, -1.48452218e-03, -7.04829573e-04,  4.56980059e-04,
        1.09923487e-03,  5.89066991e-03, -3.04335751e-02, -7.40484342e-03,
        1.65919214e-04, -3.10411499e-05,  2.63403011e-04, -7.59839291e-06,
        3.44663195e-03,  1.97316020e-06, -1.84663181e-03,  0.00000000e+00,
        3.74864899e-03, -6.49212387e-03,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.80711532e-02,
        1.52656616e-03, -3.37939800e-02,  4.17152673e-04, -1.04872547e-02,
        4.48338090e-05, -4.59107274e-04, -8.15333724e-04, -2.31593922e-03,
       -0.00000000e+00,  1.88371218e-02, -3.89103804e-04, -7.89578869e-04,
       -1.16062206e-03,  6.02030403e-05, -3.17221807e-03, -5.13887102e-05,
        3.48291649e-04,  0.00000000e+00, -6.88871086e-03, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -1.05911216e-03,
        0.00000000e+00, -1.41174023e-03,  3.56019432e-04, -0.00000000e+00,
       -8.82943339e-05,  3.51635467e-02])

In [50]:
lasso.coef_!=0

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False,  True, False,  True,  True, False,  True, False, False,
        True, False, False, False,  True,  True, False,  True,  True,
        True,  True, False, False, False,  True, False, False, False,
       False, False,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False,  True,  True, False, False, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True])

In [51]:
lasso=Lasso(alpha=100)
lasso.fit(extend_X_train,y_train)
print(lasso.score(extend_X_train,y_train))
print(lasso.score(extend_X_test,y_test))
print(np.sum(lasso.coef_!=0))#사용한 특성의 개수
#특성 사용갯수가 적어져버려서 과소적합

0.7695755624171525
0.7240159172539059
29

C:\Users\SMT063\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3.8109148352523334, tolerance: 3.1442449762532982
  model = cd_fast.enet_coordinate_descent(

In [52]:
lasso=Lasso(alpha=0.01)
lasso.fit(extend_X_train,y_train)
print(lasso.score(extend_X_train,y_train))
print(lasso.score(extend_X_test,y_test))
print(np.sum(lasso.coef_!=0))#사용한 특성의 개수

0.9180709230396541
0.7642933576942617
165

C:\Users\SMT063\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1403.5213740375013, tolerance: 3.1442449762532982
  model = cd_fast.enet_coordinate_descent(

In [53]:
lasso=Lasso(alpha=0.001)
lasso.fit(extend_X_train,y_train)
print(lasso.score(extend_X_train,y_train))
print(lasso.score(extend_X_test,y_test))
print(np.sum(lasso.coef_!=0))#사용한 특성의 개수
#특성 사용갯수가 너무 많아서 과대적합

0.9221118415709647
0.7827338664192536
177

C:\Users\SMT063\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1254.5172349603624, tolerance: 3.1442449762532982
  model = cd_fast.enet_coordinate_descent(

In [60]:
ridge=Ridge(alpha=1)
ridge.fit(extend_X_train,y_train)
print(ridge.score(extend_X_train,y_train))
print(ridge.score(extend_X_test,y_test))
print(np.sum(ridge.coef_!=0))

0.9276375855594481
0.4940990894559594
182

In [61]:
ridge=Ridge(alpha=10)
ridge.fit(extend_X_train,y_train)
print(ridge.score(extend_X_train,y_train))
print(ridge.score(extend_X_test,y_test))
print(np.sum(ridge.coef_!=0))

0.9200313276613175
0.5310393798524605
182

In [62]:
ridge=Ridge(alpha=100)
ridge.fit(extend_X_train,y_train)
print(ridge.score(extend_X_train,y_train))
print(ridge.score(extend_X_test,y_test))
print(np.sum(ridge.coef_!=0))

0.9100655692636611
0.5377172848163647
182

In [63]:
ridge=Ridge(alpha=1000)
ridge.fit(extend_X_train,y_train)
print(ridge.score(extend_X_train,y_train))
print(ridge.score(extend_X_test,y_test))
print(np.sum(ridge.coef_!=0))

0.8971453713482861
0.6571133167106584
182

In [64]:
ridge=Ridge(alpha=0.1)
ridge.fit(extend_X_train,y_train)
print(ridge.score(extend_X_train,y_train))
print(ridge.score(extend_X_test,y_test))
print(np.sum(ridge.coef_!=0))

0.9317331956416219
0.4645975232022225
182

In [65]:
ridge=Ridge(alpha=0.001)
ridge.fit(extend_X_train,y_train)
print(ridge.score(extend_X_train,y_train))
print(ridge.score(extend_X_test,y_test))
print(np.sum(ridge.coef_!=0))

0.9338850540104581
0.565896816450185
182

C:\Users\SMT063\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=4.3184e-17): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,

원래는 ridge의 alpha값이 커지면 test스코어 값이 낮아져야 정상